### ISSUE TITLE
Doneren Component

### ISSUE THREAD

**Issue by annelinderaadsheer** [fdnd-agency/red-pers#15]
De bedoeling is om een donatie component te maken met een interactie. In het nieuwe design staat de donatie knop in de header. Wanneer er op de donatie knop wordt gedrukt, komt er een popup. Ik moet het nieuwe design met het oude design combineren. 

Ook is het de bedoeling om het component "RAP/PE" te maken. 
- Responsive
- Accessible
- Performance
- Progressive Enhancement. 

![Image](https://github.com/user-attachments/assets/938ef87c-9248-49d5-bd36-e56b4262a60a)

https://github.com/user-attachments/assets/8c1060ef-c616-416b-86ee-3bd4cd3aa069

Hiervoor ga ik een morphological chart maken. Een morphological chart is een ontwerptool die wordt gebruikt om creatief problemen op te lossen en nieuwe ideeën te genereren. Een aantal ideeen van de donatie component zouden kunnen zijn:

- Ontwerp van de knop
- Locatie van de knop
- Betalingsopties 
- Bedragopties
- Wanneer Popup 
- Animatie van de knop

**Comment by RubenErhardt** [comment]
## Ontwerpen
### Morphological chart:

**Comment by RubenErhardt** [comment]
Ik denk dat ik nummer 6 het beste vindt passen, en waarbij ik het beste component kan gaan maken voor de website. Ik zit nog wel te twijfelen tussen 'scale-up' en 'fade-in'. Ik ga eerst nu een wireflow met breakdownschets maken van dit concept. En daarna ga ik dit bouwen met beide animaties. Voor nu hou ik het bij 'scale-up'.

**Comment by RubenErhardt** [comment]
## Wireflow / Breakdown

**Comment by RubenErhardt** [comment]
## Bouwen

**Comment by RubenErhardt** [comment]
Hij geeft nog steeds dezelfde foutmelding. https://html.spec.whatwg.org/multipage/popover.html#attr-popovertarget in de documentatie van w3validator staat dit zelfs.

**Comment by RubenErhardt** [comment]
Nu moeten we nog de popup stylen. Zoals je kan zien bij 

https://github.com/user-attachments/assets/8c1060ef-c616-416b-86ee-3bd4cd3aa069

In de popup zie ik een h2, een p 4 radiobuttons en een close knop.

**Comment by RubenErhardt** [comment]
Nu hebben we zoiets als dit:

https://github.com/user-attachments/assets/2ca1ede5-b7bc-4920-a12c-1ddc3d7e212f

wat ik hieraan nog moet aanpassen is:
- responsive ( vanaf pixel 460 moet alles iets kleiner )
- tabbaar maken vanaf 10 euro, ik kan mijn muis wel gebruiken als navigatie daarna, maar hij slaat 25euro en 50euro over

**Comment by RubenErhardt** [comment]
https://github.com/user-attachments/assets/d52c094b-cb0e-444f-9e87-737a684df559

issues:
- alt tekst bij imgs
- niet genoeg contrast

**Comment by RubenErhardt** [comment]
![Image](https://github.com/user-attachments/assets/ef32dbc7-d63b-492d-b941-42f263cbf910)

**Comment by RubenErhardt** [comment]
Dit moet dus nog gedaan worden:

- responsive ( vanaf pixel 460 moet alles iets kleiner )
- tabbaar maken vanaf 10 euro, ik kan mijn muis wel gebruiken als navigatie daarna, maar hij slaat 25euro en 50euro over

**Comment by RubenErhardt** [comment]
https://github.com/user-attachments/assets/364faf61-f176-46a1-8343-e06ad5b34a34

Het button component is nu volledig responsive, accessible en gebouwd volgens PE. 
Er moeten nog een aantal kleine tweaks gebeuren maar het component is zo goed als af. Tweaks zijn:
- Net iets netter maken responsive
- tabbaar tussen alle radiobuttons
- effect als er op de knop wordt geklikt

**Comment by RubenErhardt** [comment]
## CSS effect donatie knop openen 

```CSS
/* Popup animatie effect */
@keyframes popup-zoom {
    0% {
        transform: scale(0.8);
        opacity: 0;
    }
    50% {
        transform: scale(1.05);
        opacity: 1;
    }
    100% {
        transform: scale(1);
        opacity: 1;
    }
}


/* Toepassing van animatie aan de popup */
.popup {
    animation: popup-zoom 0.6s ease-out, popup-shake 0.3s ease 0.3s;
}
```

**Comment by RubenErhardt** [comment]
Laatse lighthouse test: 

![Image](https://github.com/user-attachments/assets/c980e14e-6ac0-48ef-9def-681536d24832)

https://github.com/user-attachments/assets/a325610c-b120-46a3-acda-481e4ede6885

**Comment by RubenErhardt** [comment]
## Code and design review 15/11

**Comment by Shannafdnd** [comment]
'The :popover-open [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) represents a [popover](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) element (i.e. one with a [popover attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover)) that is in the showing state. You can use this to apply style to popover elements only when they are shown.' --[https://developer.mozilla.org/en-US/docs/Web/CSS/:popover-open](https://developer.mozilla.org/en-US/docs/Web/CSS/:popover-open)

Kan je hiermee de css veranderen?

**Comment by RubenErhardt** [comment]
Test werkt 
```CSS
:popover-open {
  width: 200px;
  height: 100px;
  position: absolute;
  inset: unset;
  bottom: 5px;
  right: 5px;
  margin: 0;
}
```

![Image](https://github.com/user-attachments/assets/9db33bc4-f6ba-4f66-bc05-01d934a948ed)

Goed gevonden hier kunnen we wat mee!
