### ISSUE TITLE
Artikel component/ artikel klein

### ISSUE THREAD

**Issue by Shannafdnd** [fdnd-agency/red-pers#21]

**Comment by Shannafdnd** [comment]
## Ontwerpen
Dit is mijn mobile first design:
![Image](https://github.com/user-attachments/assets/a209980c-027e-4123-8643-ef062da70088)

Voor de desktop versie heb ik gewoon het al bestaande design van Red Pers gebruikt, namelijk;
![Image](https://github.com/user-attachments/assets/de66f96f-02da-4979-b95b-69f50e52f42d)

**Comment by Shannafdnd** [comment]
## Bouwen
Ik heb gekeken of ik container queries in dit component kon gebruiken, maar ik kwam erachter dat een normale media query gewoon beter was, omdat je de posts gewoon anders wilt vanaf een bepaalde scherm lengte, en er geen manier was hoe alleen de post zelf minder lang werd zonder dat het scherm heel erg klein werd.

### HTML
Mijn hele post zit in een a, zodat het niet uit maakt waar je op klikt. Ik heb de height en width op de image gezet, zodat het RAPPE is.

```svelte
<a href="/{post.slug}">
    <article class="article">
        <img src={post.yoast_head_json.og_image[0].url} alt="Artikel afbeelding" width="25em" height="15em">
        <div class="title-info-text">
            <div class="title">
                <h1 class="artikel-kop">{@html post.title.rendered}</h1>
            </div>
            <div class="info-text">
                <p>
                    <span class="author">{post.yoast_head_json.author}</span>
                    <span class="reading-time">
                        &minus;
                        <abbr title="Geschatte leestijd">{post.yoast_head_json.twitter_misc["Geschatte leestijd"].replace("minuten", "min")}</abbr>
                    </span>
                </p>
                <p>{(new Date(post.date)).toLocaleDateString("nl-NL", dateFormat)}</p>
            </div>
        </div>
    </article>
</a>
```

### CSS
```css
article {
        --title-font-size: 28px;
        --title-font-line-height: 32px;

        max-width: 25em;
        width: 100vw;
        border: var(--border);
    }

    img {
        width: 100%;
        height: 15em;
        border-bottom: var(--border);
    }

    h1 {
        font-family: var(--font-alt);
        font-weight: var(--font-style-bold);
        font-size: var(--title-font-size);
        line-height: var(--title-font-line-height);
        letter-spacing: 0.25px;
    }

    .title {
        width: calc(100% - 1em);
        height: 11em;
        padding: 0.5em;
        overflow: hidden;
    }

    .info-text {
        height: 2em;
        padding: 0 0.5em;

        display: flex;
        justify-content: space-between;
        align-items: center;
        
        border-top: var(--border);

        font-size: 12px;
        text-transform: uppercase;
    }

    .author {
        font-weight: bold;
    }
```

```css
@media only screen and (width < 35em) {
    article {
        max-width: unset;
        display: flex;
    }

    img {
        width: 42%;
        height: 10em;
        object-fit: cover;
        border-bottom: none;
    }

    .title-info-text {
        display: flex;
        flex-direction: column;
    }

    .title {
        height: 100%;
    }

    h1 {
        font-size: calc(var(--title-font-size) * 2 / 3); /* make font 33% smaller */
        line-height: calc(var(--title-font-line-height) * 2 / 3);
        margin: 0;
    }

    .info-text {
        border-top: none;
        padding: 0 0.5em;
        font-size: 12px;
    }

    .reading-time {
        display: none;
    }
}
```

### JS
Ik heb maar een heel klein stukje js gebruikt, om de datum goed neer te zetten. Ik heb erover nagedacht om een js functie te schrijven voor een ellipse, voor wanneer de titel te lang is. Maar ik zag dat een lange titel bijna niet voor kwam, dus heb besloten dat dit een could have issue kon worden. 

```js
 export let post

    const dateFormat = {
        month: 'short',
        day: 'numeric',
    };
```
