### ISSUE TITLE
Donation-box component

### ISSUE THREAD

**Issue by Shannafdnd** [fdnd-agency/red-pers#25]

**Comment by RubenErhardt** [comment]
Met een beetje CSS komen we al een heel eind.

```CSS
<style>
main{
    --red-main:#E85340;
    --red-main-light: #F9D4CF;
    --red-main-lightest:#FFF4F2;
}

h3{
    color: var(--red-main);
}

p{
    color: var(--red-main);
    padding: 20px;
}

button{
    background-color: var(--red-main-light);
    color: var(--red-main);
}

.donatiebox{
    background-color: var(--red-main-lightest);
    outline: 1px solid var(--red-main);
}

.donatie-bedragen{
    padding: 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.donatie-bedragen button{
    width: 23%;
    margin-top: -60px;
}

.andere-donatie{
    padding: 20px;
    margin-top: -50px;
}

.andere-donatie button{
    width: calc(4 * 25%);
}
</style>
```
![Image](https://github.com/user-attachments/assets/e8569035-ea2a-4556-ac39-1fdcd682316a)
