### ISSUE TITLE
(S18) Voorpagina verbeteren

### ISSUE THREAD

**Issue by RubenErhardt** [fdnd-agency/red-pers#69]
Ik ga nu de voorpagina verbeteren, met als doel het meest recente artikel meer op de voorgrond te plaatsen. Dit artikel verdient een prominente plek, zodat bezoekers meteen worden meegenomen in de nieuwste en meest relevante content. Door de opzet en indeling van de voorpagina strategisch aan te passen, wil ik de zichtbaarheid en betrokkenheid verhogen. 

Huidig: 

![Image](https://github.com/user-attachments/assets/a2918420-fd7c-4bab-939a-d2b2c5f35953)

Nieuw design:

![Image](https://github.com/user-attachments/assets/d837cab3-4803-47b7-aee8-d13b13cca02f)

**Comment by RubenErhardt** [comment]
De bedoeling is dus om het eerste artikel te targetten, de rest van de artikelen is in principe goed.

**Comment by RubenErhardt** [comment]
Met een beetje eigen design ben ik op dit resultaat gekomen

![Image](https://github.com/user-attachments/assets/9cd49541-9d79-41af-b79a-f3c2a6daf368)

**Comment by RubenErhardt** [comment]
Nog wat kleine aanpassingen

![Image](https://github.com/user-attachments/assets/1bd614a5-0b44-4847-80d7-5ec14ec522a1)

De code ziet er als volgt uit:

```HTML
<a href="/{post.slug}">
    <article class="article {isFirst ? 'first-article highlighted' : 'other-articles'}" 
        style={isFirst ? 'max-width:1240px' : 'max-width: 25em;'}>

        <!-- Voeg hier de badge toe voor het nieuwste artikel -->
        {#if isFirst}
        <div class="newest">NIEUWSTE ARTIKEL</div>
        {/if}
        
        <img loading="lazy" src={post.yoast_head_json.og_image[0].url} alt="Artikel afbeelding" width="25em" height="15em">
        
        <div class="title-info-text">
            <div class="title">
                <h1 class="artikel-kop">{@html post.title.rendered}</h1>
            </div>
            
            <!-- Excerpt alleen zichtbaar als het eerste artikel is -->
            {#if isFirst}
                <p class="excerpt">{@html post.excerpt.rendered}</p>
            {/if}

            <div class="info-text">
                <p>
                    <span class="author">{post.yoast_head_json.author}</span>
                    <span class="reading-time">
                        <span aria-hidden="true">&minus;</span>
                        <abbr title="Geschatte leestijd">
                            {post.yoast_head_json.twitter_misc["Geschatte leestijd"]?.replace("minuten", "")}
                            <span aria-label="minuten">min</span>
                        </abbr>
                    </span>
                </p>
                <p>{(new Date(post.date)).toLocaleDateString("nl-NL", dateFormat)}</p>
            </div>

        </div>
    </article>
</a>
```

```CSS

<style>

    img {
        width: 100%;
        height: 15em;
        border-bottom: var(--border);
    }

    h1 {
        font-family: var(--font-alt);
        font-weight: var(--font-style-bold);
        font-size: var(--title-font-size);
        line-height: var(--title-font-line-height);
        letter-spacing: 0.25px;
    }

    .title {
        width: calc(100% - 1em);
        height: 11em;
        padding: 0.5em;
        overflow: hidden;
    }

    .first-article .excerpt {
    font-size: 16px; /* Pas eventueel de lettergrootte aan voor de excerpt */
    margin-top: -5em;
    line-height: 1.5;
}

    .info-text {

        display: flex;
        justify-content: space-between;
        align-items: center;
        
        border-top: var(--border);

        font-size: 12px;
        text-transform: uppercase;
    }

    .author {
        font-weight: bold;
    }

@media only screen and (width < 35em) {
    article {
        max-width: unset;
        display: flex;
    }

    img {
        width: 42%;
        height: 10em;
        object-fit: cover;
        border-bottom: none;
    }

    .title-info-text {
        display: flex;
        flex-direction: column;
    }

    .title {
        height: 100%;
    }

    h1 {
        font-size: calc(var(--title-font-size) * 2 / 3); /* make font 33% smaller */
        line-height: calc(var(--title-font-line-height) * 2 / 3);
        margin: 0;
    }

    .info-text {
        border-top: none;
        padding: 0 0.5em;
        font-size: 12px;
    }

    .reading-time {
        display: none;
    }
}

.other-articles {
        --title-font-size: 28px;
        --title-font-line-height: 32px;
        max-width: 25em;
        border: var(--border);
        background-color: var(--background-color);
    }


    .first-article {
        display: flex;
        margin-top: 20px;
        position: relative;
        flex-direction: row;  /* Zorgt ervoor dat afbeelding en tekst naast elkaar staan */
        gap: 1em;
        border-left: 4px solid #D5302D; /* Rode lijn aan de linkerkant voor accent */
        background-color: var(--background-color);
        max-width: 1240px;
        margin-bottom: 1.5em;
        box-sizing: border-box;
        transition: transform 0.3s ease, box-shadow 0.3s ease; /* Zachte overgang voor de hover-effecten */
    }

    .first-article .newest {
    position: absolute;
    top: 10px;
    left: 10px;
    background-color: rgba(255, 0, 0, 0.7); /* Rood met doorzichtige achtergrond */
    color: white;
    font-size: 14px;
    padding: 5px 10px;
    font-weight: bold;
    text-transform: uppercase;
    border-radius: 3px;
}

    .first-article img {
        width: 100%;
        height: 26em;
        border-bottom: var(--border);
        object-fit: cover; /* Zorgt ervoor dat de afbeelding niet uitgerekt wordt */
    }

    .first-article h1 {
        font-family: var(--font-alt);
        font-weight: var(--font-style-bold);
        font-size: var(--title-font-size);
        line-height: var(--title-font-line-height);
        letter-spacing: 0.25px;
        transition: color 0.3s ease; /* Zachte overgang voor kleurverandering bij hover */
    }

    .first-article .title {
        width: calc(100% - 1em);
        height: 11em;
        padding: 0.5em;
        overflow: hidden;
    }

    .first-article .info-text {
        height: 2em;
        padding: 0 0.5em;
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 14px;
        text-transform: uppercase;
    }

    .first-article .author {
        font-weight: bold;
    }

    .first-article {
        --title-font-size: 28px;
        --title-font-line-height: 32px;
        border: var(--border);
        background-color: var(--background-color);
        margin-bottom: 1.5em;
        box-sizing: border-box;
        border-left: 4px solid red;
        max-width: 1240px;
    }

    /* Hover effect */
    .first-article:hover {
        transform: scale(1.02);  /* Vergroot het artikel subtiel */
    }


    /* Media Query voor mobiele apparaten */
    @media only screen and (max-width: 768px) {
        .first-article {
            flex-direction: column;  /* Zorgt ervoor dat afbeelding en tekst onder elkaar staan op mobiele schermen */
            gap: 1em;
        }

        .first-article img {
            width: 100%;  /* Afbeelding neemt de volledige breedte in op mobiel */
            height: auto;
        }
    }
</style>
```
